package com.robustrade.wallet.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Double-entry ledger row. Indexes mirror Flyway ({@code V1} transfer_id index,
 * {@code V3} composite wallet chronological index); schema is not generated by Hibernate.
 */
@Entity
@Table(
        name = "ledger_entries",
        indexes = {
                @Index(
                        name = "ledger_entries_wallet_created_id_idx",
                        columnList = "wallet_id, created_at, id"
                ),
                @Index(name = "ledger_entries_transfer_id_idx", columnList = "transfer_id")
        },
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "ledger_entries_transfer_type_uk",
                        columnNames = {"transfer_id", "transaction_type"}
                )
        }
)
@Getter
@Setter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
@Builder
public class LedgerEntry {

    @Id
    @Column(name = "id", nullable = false)
    private UUID id;

    @Column(name = "wallet_id", nullable = false, length = 36)
    private String walletId;

    @Column(name = "transfer_id", nullable = false)
    private UUID transferId;

    @Enumerated(EnumType.STRING)
    @Column(name = "transaction_type", nullable = false, length = 16)
    private TransactionType transactionType;

    @Column(name = "amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal amount;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    public static LedgerEntry debit(String walletId, UUID transferId, BigDecimal amount) {
        return of(walletId, transferId, TransactionType.DEBIT, amount);
    }

    public static LedgerEntry credit(String walletId, UUID transferId, BigDecimal amount) {
        return of(walletId, transferId, TransactionType.CREDIT, amount);
    }

    private static LedgerEntry of(
            String walletId,
            UUID transferId,
            TransactionType type,
            BigDecimal amount
    ) {
        return LedgerEntry.builder()
                .id(UUID.randomUUID())
                .walletId(walletId)
                .transferId(transferId)
                .transactionType(type)
                .amount(amount)
                .createdAt(Instant.now())
                .build();
    }
}
